[package]
name = "rsel4"
version = "0.1.0"
edition = "2021"


[build-dependencies]
liquid = "0.26.6"

[dependencies]
polyhal = { git = "https://github.com/Byte-OS/polyhal.git" }
buddy_system_allocator = "0.9.1"
